packaging_format = 2

id = "ssbroom"
name = "Scuttlebutt Room"
description.en = "Secure Scuttlebutt room server implemented in Go"

version = "2.0.6~ynh5"

maintainers = ["Max Fowler"]

[upstream]
license = "free"
website = "https://github.com/ssb-ngi-pointer/go-ssb-room"
demo = "https://hermies.club/"
admindoc = "https://github.com/ssb-ngi-pointer/go-ssb-room/blob/master/README.md"
userdoc = "https://github.com/ssb-ngi-pointer/go-ssb-room/blob/master/README.md"
code = "https://github.com/ssb-ngi-pointer/go-ssb-room"

[integration]
yunohost = ">= 11.1.19"
architectures = ["amd64", "arm64", "armhf"]
multi_instance = true
ldap = false
sso = false
disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"
    full_domain = true

    [install.init_main_permission]
    help.en = "If false, ssbroom will only be usable by yunohost users."
    type = "group"
    default = "visitors"

    [install.ssb_admin_id]
    ask.en = "SSB ID of first admin of the room"
    help.en = "This ssb_id is used as the username for the first admin of the room. Create an ssb account or use your already existing ssb account, and use your ssb public key as the room admin id."
    type = "string"
    example = "@5Pt3dKy2HTJ0mWuS78oIiklIX0gBz6BTfEnXsbvke9c=.ed25519"

    [install.password]
    help.en = "Use this password to log into the admin interface for the ssb room."
    type = "password"

[resources]
        [resources.sources.main]
        armhf.url = "https://files.commoninternet.net/go-ssb-room_2.0.6_Linux_arm7.tar.gz"
        armhf.sha256 = "8894b7b21031976e1d79265fefdcef4edb6fde38f34231e8aea4cebcc85a4f88"
        arm64.url = "https://files.commoninternet.net/go-ssb-room_2.0.6_Linux_aarch64.tar.gz"
        arm64.sha256 = "8f9d357d54fd8bdc1c2e906919ddefef21ae51b13e5ae1939424c6c1e94c9d23"
        amd64.url = "https://files.commoninternet.net/go-ssb-room_2.0.6_Linux_amd64.tar.gz"
        amd64.sha256 = "1a1c4368df219e907e15996bd6d62b653f54017993b1cc607ab09a9a01fb8558"

    [resources.ports]
    main.default = 8899
    ssb.default = 8008
    ssb.exposed = "TCP"

    [resources.system_user]

    [resources.install_dir]

    [resources.data_dir]

    [resources.permissions]
    main.url = "/"

    [resources.apt]
    packages = "expect"
