test_format = 1.0

[default]

    # -------------------------------
    # Default args to use for install
    # -------------------------------

	args.ssb_admin_id="@5Pt3dKy2HTJ0mWuS78oIiklIX0gBz6BTfEnXsbvke9c=.ed25519"

    # -------------------------------
    # Commits to test upgrade from
    # -------------------------------

    test_upgrade_from.c759c5f400660031676a0f92d5c5ffcc68bd6da9.name = "Upgrade from 2.0.6~ynh3"
